development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8983/fedora/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8983/fedora/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "http://#{ENV['HYDRAPRODUCTIONFEDORA_PORT_8080_TCP_ADDR']}:8080/fcrepo-webapp-4.1.1/rest" %>
  base_path: /prod
